name: Deploy Old

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Deploy to pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install
        run: yarn
      - name: Build
        run: yarn build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.8
        with:
          path: dist
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
